### ISSUE TITLE
[Suggestion]: Enabling special music tracks for certain mobs

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/mob-battle-music#11]
### Description of feature request

Allow people to configure special music tracks to play only when fighting certain mobs or mobs in a tag. For instance a special track that only plays when fighting nether mobs or endermen.

**Comment by TSEG6** [comment]
This was already added with the latest update.
You can do this with resource packs. Be sure to read the [wiki](https://github.com/nonamecrackers2/mob-battle-music/wiki/Customization) linked here.

**Comment by BluePineappleGuy** [comment]
> This was already added with the latest update. You can do this with resource packs. Be sure to read the [wiki](https://github.com/nonamecrackers2/mob-battle-music/wiki/Customization) linked here.

Thx, didn't know you could. closing this now then
