### ISSUE TITLE
[Suggestion]: Entity based Music

### ISSUE THREAD

**Issue by scarletgoon06** [nonamecrackers2/mob-battle-music#19]
### Description of feature request

being able to make certain mobs also have different music would be a great thing for mods that add more threatening mobs for example music for when you're chased down by an Enderman. 
since there's a blacklist feature maybe use something similar to be able to give different mobs custom music.

**Comment by TSEG6** [comment]
Pretty sure this is already a feature, you need to look in the GitHub wiki for a guide

**Comment by scarletgoon06** [comment]
i indeed found it on the wiki. thanks. though i can't exactly figure it out... i'm not really familiar with coding of any kind. i usually just use an example file and replace the music.

**Comment by TSEG6** [comment]
I suggest closing this issue then

**Comment by nonamecrackers2** [comment]
There are example files at the bottom of the wiki doc
