### ISSUE TITLE
[Bug]: Wither Storm seen through the ground with darkness effect

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/mob-battle-music#22]
### Mod Version

1.20.1-1.1.1.2

### Mod Loader

Forge

### Mod Loader Version

Nothing to do with this issue

### Describe the bug

Title explains it

### Steps to Reproduce

1. summon wither storm (preferably in phase4+)
2. add darkness effect
3. see error

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/mob-battle-music/assets/114537009/693e570e-ac2f-4114-a95d-d35f0d9d496d)

### Mod List

CWSM and other mods that have nothing to do with the issue

**Comment by GearsawStudios** [comment]
Wrong github.

**Comment by Pandaboi25x** [comment]
> Wrong github.

what

**Comment by Pandaboi25x** [comment]
anyways sure wonder whos in the ancient city

**Comment by TaintedBlock** [comment]
whoops, wrong github

**Comment by Pandaboi25x** [comment]
OH LOL
