### ISSUE TITLE
[Suggestion]: can't I have the example resource pack

### ISSUE THREAD

**Issue by SparklingBouquet** [nonamecrackers2/mob-battle-music#24]
### Description of feature request

I try replacing existing tracks as tutorial but I can't understand why there aren't any resource pack showing to add in the game

**Comment by TSEG6** [comment]
There are example resource packs and a walkthrough of how to customize the mod located [here](https://github.com/nonamecrackers2/mob-battle-music/wiki/Customization).

**Comment by SparklingBouquet** [comment]
![image](https://github.com/nonamecrackers2/mob-battle-music/assets/172389559/a8f6158d-0397-4d9e-8540-482f9a66ae00)
Am I doing it wrong?

**Comment by nonamecrackers2** [comment]
Your resource pack is not valid, the assets folder should be in a separate folder instead of the "resourcepacks" folder. Please learn how to set up a resource pack or use one of the examples the guide gives.
