### ISSUE TITLE
[Bug]: Player aggro music does not play

### ISSUE THREAD

**Issue by qwertyey** [nonamecrackers2/mob-battle-music#3]
### Minecraft Version

1.20.1

### Mod Version

1.0

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

Player aggro music does not play at all

### Steps to Reproduce

1. Get hit by player/hit another player
2. No music plays

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Essential
Mod Battle Music

**Comment by TSEG6** [comment]
Pretty sure this was resolved

**Comment by nonamecrackers2** [comment]
Yeah, make sure you're hitting the player with a weapon since that's the only way it'll go off
