### ISSUE TITLE
[Bug]: help, how i can see mob tag?

### ISSUE THREAD

**Issue by NVKknight** [nonamecrackers2/mob-battle-music#32]
### Mod Version

1.20.1-1.1.1.2

### Mod Loader

Forge

### Mod Loader Version

na

### Describe the bug

i investigate much and i no have result whit this, how i can see mob tag for the mod?
this is not a bug

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

none

**Comment by GearsawStudios** [comment]
Please don’t use this as a help forum, use the Discord instead.

**Comment by NVKknight** [comment]
thanks
