### ISSUE TITLE
[Suggestion]: head of the wither storm

### ISSUE THREAD

**Issue by Zakhar2009** [nonamecrackers2/mob-battle-music#37]
### Description of feature request

**there is an idea for a mod: add a storm wither head in the form of a block that can be hung on the wall and if you connect and turn on redstone, then a beam will appear from his eye that sucks mobs to itself, when a mob flies up to the head, it will attack 1 heart per second, but it will not be difficult to escape from this beam, and you can not hit the head, only break it**

**Comment by TSEG6** [comment]
Wrong GitHub page for this, this isn't crackers wither storm lol.
