### ISSUE TITLE
[Suggestion]: Player Track plays whenever a player is punched by another

### ISSUE THREAD

**Issue by TaintedBlockmObile** [nonamecrackers2/mob-battle-music#4]
### Description of feature request

Instead of it being limited to a sword it should be when the player is directly punched with anything since in a lot of situations it can be counted as fighting

**Comment by nonamecrackers2** [comment]
But in some situations you're not actually fighting them so it wouldn't make sense for the music to play. We'll add a config option for this since I feel players would be split on it.

**Comment by nonamecrackers2** [comment]
Config option will be implemented in the next major release
