### ISSUE TITLE
[Suggestion]: allow resource packs to add multiple songs for each condition

### ISSUE THREAD

**Issue by roffwizard** [nonamecrackers2/mob-battle-music#6]
Hey, I am a modpack maker and I was wondering if it is possible for you to add multiple songs to each condition, or allow a config option to be tweaked to allow more song options for each category if added by resource packs.

**Comment by WitherBean** [comment]
You already can with a sounds.json file if I know what you mean.

**Comment by nonamecrackers2** [comment]
If you're thinking about adding multiple sections of music that play depending on certain conditions for each track type, that's not possible currently. If you're just wanting each track type to play a random different sound file whenever the song begins, you can do that with a resource pack modifying the mods ``sounds.json`` file:

```
{
	"non_aggro_track":
	{
		"category": "records",
		"sounds":
		[
			{ 
				"name": "mobbattlemusic:non_aggro_track",
				"stream": true,
				"volume": 0.6
			}
		]
	},
	"aggro_track":
	{
		"category": "records",
		"sounds":
		[
			{ 	
				"name": "mobbattlemusic:aggro_track",
				"stream": true,
				"volume": 0.6
			},
			{ 	
				"name": "mobbattlemusic:aggro_track_1",
				"stream": true,
				"volume": 0.6
			},
			{ 	
				"name": "mobbattlemusic:aggro_track_2",
				"stream": true,
				"volume": 0.6
			}
		]
	},
	"player_track":
	{
		"category": "records",
		"sounds":
		[
			{
				"name": "mobbattlemusic:player_track",
				"stream": true,
				"volume": 0.6
			},
			{
				"name": "mobbattlemusic:player_track_1",
				"stream": true,
				"volume": 0.6
			}
		]
	}
}
```
The above is just an untested example of what you can do.
