### ISSUE TITLE
[Bug]: Blacklist doesn't Work for Aggressive Music

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [nonamecrackers2/mob-battle-music#9]
### Minecraft Version

1.20.1

### Mod Version

1.0

### Mod Loader

Forge

### Mod Loader Version

47.2.21

### Describe the bug

The Aggressive Music starts playing when you attacking a Blacklisted Mob

(Mod is Version "1.1.1-all.jar", option was not present in Mod Version Section, so clarifying that here)

### Steps to Reproduce

1. Spawn or Find a mob that's been added to the blacklist (by default, Creeper)
2. Attack it with a weapon
3. Music starts playing despite the Mob being blacklisted

currently, the blacklist is only blocking the nonaggressive music

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Tested with only Mob Battle Music Installed, with both the default and a modified config with additional vanilla mobs added.

**Comment by nonamecrackers2** [comment]
This is technically intended, it’s so when a creeper explodes and damages you it’ll still cause the music to play. I could probably sort something out however.

**Comment by AlexTheSuprWolf** [comment]
please do. with the way it currently is, there is no way to disable it entirely for the vanilla bosses and other entities. alot of modded bosses also have music nowadays too, so having a way to turn it off completely for those entities would be nice.

a second whitelist would probably be the best solution, the current one for non-aggressive music and a new one for aggressive music.
